url: "https://jiahao-zeng.github.io"
baseurl: "/Math-497-Final-Project"
title: "Math 497 Final Project"
description: "Mathematical Modeling and Analysis"
markdown: kramdown

kramdown: 
  input: GFM
  math_engine: mathjax
  parse_block_html: true
  math_engine_opts:
    preview: false

sass:
  style: compressed
  sass_dir: assets/css

defaults:
  - scope:
      path: ""
      type: "pages"
    values: 
      layout: default
  - scope:
      path: "handouts"
      type: "pages"
    values:
      layout: handout