url: "https://jiahao-zeng.github.io"
baseurl: "/Math-497-Final-Project"
theme: jekyll-theme-minimal
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  parse_block_html: true
  math_engine_opts:
    preview: TeX
